backend:
  name: git-gateway
  branch: main # NOTE this relates to your GitHub branch
publish_mode: editorial_workflow
local_backend: true # allows for you to locally mess with your CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
  preview: false # we're going to hide the preview editor
collections:
  - name: "segmentation-data"
    label: "Segmentation Data"
    files:
      - name: "post-categories"
        label: "Post Categories"
        format: "json"
        extension: "json"
        file: "src/data/post-categories.json"
        fields:
          - name: "categories-list"
            label: "List"
            widget: "list"
            collapsed: true
            label_singular: "category"
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                pattern:
                  [
                    "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "A url can have no spaces or special characters",
                  ]
              - label: "Label"
                name: "label"
                widget: "string"
              - label: "Color"
                name: "color"
                widget: "color"
                allowInput: true
              - label: "Image"
                name: "image"
                widget: "image"
                allow_multiple: false
                choose_url: false

      - name: "learnings"
        label: "Learnings"
        format: "json"
        file: "src/data/learnings.json"
        fields:
          - name: "learnings-list"
            label: "Learnings list"
            widget: "list"
            fields:
              - label: "slug"
                name: "Slug"
                pattern:
                  [
                    "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "A url can have no spaces or special characters",
                  ]
              - label: "Label"
                name: "label"
                widget: "string"
              - label: "Color"
                name: "color"
                widget: "color"
      - name: "snippets-types"
        label: "Snippets types"
        format: "json"
        file: "src/data/snippets-types.json"
        fields:
          - name: "snippets-types-list"
            label: "Snippets types list"
            widget: "list"
            fields:
              - label: "slug"
                name: "Slug"
                pattern:
                  [
                    "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "A url can have no spaces or special characters",
                  ]
              - label: "Label"
                name: "label"
                widget: "string"

  - name: "categories"
    label: "Post Category"
    folder: "src/data/categories"
    create: true
    slug: "{{slug}}"
    identifier_field: label
    format: json
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Color", name: "color", widget: "color", allowInput: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
          choose_url: false,
        }
      - label: "City"
        name: "city"
        widget: "relation"
        collection: "segmentation-data"
        file: "post-categories"
        search_fields: ["categories-list.*.label"]
        display_fields: ["categories-list.*.label"]
        value_field: "categories-list.*.label"
